### ISSUE TITLE
Cannot Connect to Database

### ISSUE THREAD

**Issue by mmc102** [wasp-lang/open-saas#54] opened 2024-02-23 14:21 UTC
I made sure I had the db running in one shell:
```
~/Projects/food_truck/open-saas/app $ wasp start db
✨ Starting a PostgreSQL dev database (based on your Wasp config) ✨

Additional info:
 ℹ Connection URL, in case you might want to connect with external tools:
     postgresql://postgresWaspDevUser:postgresWaspDevPass@localhost:5432/SaaSTemplate-c879beb36e
 ℹ Database data is persisted in a docker volume with the following name (useful to know if you will want to delete it at some point):
     wasp-dev-db-SaaSTemplate-c879beb36e

...

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-02-23 14:06:51.382 UTC [1] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-02-23 14:06:51.382 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-02-23 14:06:51.382 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-02-23 14:06:51.383 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-23 14:06:51.386 UTC [28] LOG:  database system was shut down at 2024-02-23 14:06:29 UTC
2024-02-23 14:06:51.388 UTC [1] LOG:  database system is ready to accept connections
2024-02-23 14:11:51.481 UTC [26] LOG:  checkpoint starting: time
2024-02-23 14:11:51.496 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.002 s, total=0.016 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
```

confirmed the ports are correct:

```
~/Projects/food_truck/open-saas/app $ docker ps
CONTAINER ID   IMAGE      COMMAND                  CREATED         STATUS         PORTS                    NAMES
234e2b584710   postgres   "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes   0.0.0.0:5432->5432/tcp   wasp-dev-db-SaaSTemplate-c879beb36e
```

but I still am unable to connect to the db:

```
~/Projects/food_truck/open-saas/app $ wasp db migrate-dev

🐝 --- Compiling wasp project... --------------------------------------------------


🐝 --- Setting up database... -----------------------------------------------------


✅ --- Database successfully set up. ----------------------------------------------


✅ --- Your wasp project has successfully compiled. -------------------------------



❌ --- [Error] Can not connect to database: ---------------------------------------

The database needs to be running in order to execute this command. You can easily start a managed dev database with `wasp start db`.

```

I can just nuke and restart, but I dont think i've changed very many things beyond the landing page, so I would like to learn how to troubleshoot this in the future if i get an app more built out. 

😅 sorry if this is something obvious and im just missing it.

**Comment by Martinsos** [comment] 2024-02-23 16:06
@mmc102 is it possible that you have something else running on port 5432? FOr example, native postgres process? What happens is, even though Docker forwards 5432 to 5432, if there is something else running on 5432, Docker's forwarding won't come through, being shadowed over by whatever else is running on that port. Here is how you can find out who is already on that port: https://stackoverflow.com/a/3855359/1509394 .

I can't really think of anything else at the moment -> give this a try and let's see if it is the cause!
And a bit silly question, but you do keep your terminal tab running `wasp db start` active while doing all this, right?

**Comment by mmc102** [comment] 2024-02-23 16:22
thanks for the response!!

I tried killing anything running on that port (though it looks like its the docker container):

```
matts-mbp-8:app mattcarroll$ sudo lsof -i :5432
COMMAND     PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 50398 mattcarroll  138u  IPv6 0xab3b9fd80e35e5d7      0t0  TCP *:postgresql (LISTEN)
matts-mbp-8:app mattcarroll$ kill 50398
matts-mbp-8:app mattcarroll$ sudo lsof -i :5432
matts-mbp-8:app mattcarroll$ 
```
restart the container with the db:

```
~/Projects/food_truck/open-saas/app $ wasp start db
✨ Starting a PostgreSQL dev database (based on your Wasp config) ✨

Additional info:
 ℹ Connection URL, in case you might want to connect with external tools:
     postgresql://postgresWaspDevUser:postgresWaspDevPass@localhost:5432/SaaSTemplate-c879beb36e
 ℹ Database data is persisted in a docker volume with the following name (useful to know if you will want to delete it at some point):
     wasp-dev-db-SaaSTemplate-c879beb36e

...

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-02-23 16:15:28.966 UTC [1] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-02-23 16:15:28.967 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-02-23 16:15:28.967 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-02-23 16:15:28.968 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-23 16:15:28.970 UTC [28] LOG:  database system was interrupted; last known up at 2024-02-23 16:10:47 UTC
2024-02-23 16:15:29.028 UTC [28] LOG:  database system was not properly shut down; automatic recovery in progress
2024-02-23 16:15:29.029 UTC [28] LOG:  redo starts at 0/2C12718
2024-02-23 16:15:29.029 UTC [28] LOG:  invalid record length at 0/2C12800: wanted 24, got 0
2024-02-23 16:15:29.029 UTC [28] LOG:  redo done at 0/2C127C8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2024-02-23 16:15:29.031 UTC [26] LOG:  checkpoint starting: end-of-recovery immediate wait
2024-02-23 16:15:29.034 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.003 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
2024-02-23 16:15:29.039 UTC [1] LOG:  database system is ready to accept connections
```

*leave this open and start another terminal* 

*confirm docker is running*
```
Matts-MacBook-Pro-8:app mattcarroll$ docker ps
CONTAINER ID   IMAGE      COMMAND                  CREATED          STATUS          PORTS                    NAMES
d185bbcab16a   postgres   "docker-entrypoint.s…"   12 seconds ago   Up 11 seconds   0.0.0.0:5432->5432/tcp   wasp-dev-db-SaaSTemplate-c879beb36e


looks like the port is bound to the docker container
```
Matts-MacBook-Pro-8:app mattcarroll$ lsof -i tcp:5432
COMMAND     PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 33330 mattcarroll  185u  IPv6 0xab3b9fd80e360dd7      0t0  TCP *:postgresql (LISTEN)
```

```
Matts-MacBook-Pro-8:app mattcarroll$ wasp start

🐝 --- Starting compilation and setup phase. Hold tight... ------------------------


🐝 --- Compiling wasp project... --------------------------------------------------


🐝 --- Setting up database... -----------------------------------------------------


✅ --- Database successfully set up. ----------------------------------------------


✅ --- Your wasp project has successfully compiled. -------------------------------



❌ --- [Error] Can not connect to database: ---------------------------------------

The database needs to be running in order to execute this command. You can easily start a managed dev database with `wasp start db`.

```
I'm sure this is something silly on my end.

**Comment by mmc102** [comment] 2024-02-23 16:29
ok this is kind of interesting:

```
psql  postgresql://postgresWaspDevUser:postgresWaspDevPass@localhost:5432/SaaSTemplate-c879beb36e
psql: error: could not translate host name "localhost" to address: nodename nor servname provided, or not known

Matts-MacBook-Pro-8:MobileMenu mattcarroll$ psql  postgresql://postgresWaspDevUser:postgresWaspDevPass@0.0.0.0:5432/SaaSTemplate-c879beb36e
```

if i try to use the url provided by the start db command it doesnt work, but if i sub it out for 0.0.0.0 its all good.

**Comment by mmc102** [comment] 2024-02-23 16:34
ok I figured it out. I had to update `etc/hosts`:

Matts-MacBook-Pro-8:etc mattcarroll$ sudo vim hosts
```
   # Added by Docker Desktop
   # To allow the same kube context to work on the host and the container:
   # 127.0.0.1 kubernetes.docker.internal  <----- i had to comment this out
   127.0.0.1 localhost <----- i had to add this
   # End of section
```

probably some hack from me doing something weird at a previous time! 😅

**Comment by vincanger** [comment] 2024-02-26 15:04
glad you got it working @mmc102 -- closing this issue now :)

**Closed by vincanger** 2024-02-26 15:04 UTC

**Comment by DreamerAmit** [comment] 2024-09-09 07:53
> ok I figured it out. I had to update `etc/hosts`:
> 
> ```
>    # Added by Docker Desktop
>    # To allow the same kube context to work on the host and the container:
>    # 127.0.0.1 kubernetes.docker.internal  <----- i had to comment this out
>    127.0.0.1 localhost <----- i had to add this
>    # End of section
> ```
> 
> probably some hack from me doing something weird at a previous time! 😅

Hi @mmc102 Cant thank you enough, After spending 2 hours, I was able to get to your comment and solved this issue quickly. Thank You so much for posting..Hadnt you not posted this, I would have given up!

**Comment by Martinsos** [comment] 2024-09-09 10:26
I am glad it helped!

By default, on Mac, localhost should be pointing to 127.0.0.1 , so I think we should be ok with our command. @mmc102 any idea how is that you didn't have this set on your system? I am wondering if it is common occurence, should we do something about it on our side.

**Comment by deeplight77** [comment] 2024-10-11 17:28
Docker desktop adds this entry to the hosts file:

# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
