### ISSUE TITLE
Can i add a asset for the server side, a folder a config file etc?

### ISSUE THREAD

**Issue by bababuluba** [wasp-lang/open-saas#47] opened 2024-02-16 06:58 UTC

**Comment by vincanger** [comment] 2024-02-16 08:57
closing this as its a duplicate of a [question in discord ](https://discord.com/channels/686873244791210014/1207945143496343552/1207945143496343552)

**Closed by vincanger** 2024-02-16 08:57 UTC

**Comment by Martinsos** [comment] 2024-02-16 11:26
Related to https://github.com/wasp-lang/wasp/issues/1564
