### ISSUE TITLE
Multi Tenancy Feature

### ISSUE THREAD

**Issue by chakravarthi-bb** [wasp-lang/open-saas#222] opened 2024-07-08 15:22 UTC
If this template has a multi-tenancy feature that would be great

**Comment by Martinsos** [comment] 2024-07-08 15:24
Duplicate of https://github.com/wasp-lang/wasp/issues/2129! @chakravarthi-bb , I am quite interested to hear more about what exactly you would need from multi-tenancy, could you please write morea bout it in the issue I linked? What exactly would you like: multiple databases I guess? Something else? All info helps!

**Closed by Martinsos** 2024-07-08 15:24 UTC

**Comment by chakravarthi-bb** [comment] 2024-07-08 18:31
These are the features I am looking for

- Serve multiple customers across different subdomains/custom domains with a single unified codebase
- Multiple Databases approach might be overkill, I am ok with single database shared schema or single database with single schema
- Fix Auth based on Server URL, as different custom domains will enable different logins and each sub domain should be redirected to the sub domain instead of main domain

I will keep on adding more to this list
