### ISSUE TITLE
Our domain opensaas.sh got blacklisted due to shared dynamic IP and we can't get rid of it

### ISSUE THREAD

**Issue by joeygeo** [wasp-lang/open-saas#172] opened 2024-06-08 11:47 UTC
Why is Avast antivirus saying that opensaas.sh website is malicious? You may want to check with them for false positives.

**Comment by Martinsos** [comment] 2024-06-08 16:33
Hm that is silly! Does it give any extra information? How can we reproduce this: install Avast on Windows and open opensaas.sh in Chrome?

**Comment by joeygeo** [comment] 2024-06-08 16:49
Yes exactly those steps. I am attaching a scrshot. 
I am using Brave browser in this case, but already tried with Chrome, and has the same issue.
Just check virus total and that also lists one security Vendor : https://www.virustotal.com/gui/url/9ff89c2363f8b07c1a03313e0565d556dee978934748e0c8ce097b9bfd7826cc

![image](https://github.com/wasp-lang/open-saas/assets/12219781/36b83163-778d-4843-b903-f282792a2532)

**Comment by Martinsos** [comment] 2024-06-10 11:29
This is great, thanks! So I told it to run analysis again, and now I got all good! Was it some temporary false positive on their side?

![image](https://github.com/wasp-lang/open-saas/assets/1536647/0012ace7-89f1-47b3-936c-349d20e20ecb)

@joeygeo could you also pls check on your side again, if it also tells you all is good now? I will close the issue for now, but if it is till reporting an issue for you, let me know and I will reopen it.

**Comment by Martinsos** [comment] 2024-06-10 17:34
> VirusTotal looks fine, but Avast still says blacklisted. I have raised a false positive report with them... That may take a few days... I will report back what they say.
> 
> Weirdly enough, even the emails that are coming from github for this repo is marked as suspicious... Note that I do get comments from other github repos, and they are clean.

Thanks for making that report! Ok let's see, if needed we can also try reaching out to them and try to figure out what is causing this. Would be great if we can somehow get an insight on what is triggering this, maybe .sh extension?

**Comment by joeygeo** [comment] 2024-06-10 18:09
Unlikely.. its mostly the content of HTML generated by a website. Check all external links in your website code.

**Comment by Martinsos** [comment] 2024-06-10 18:24
Thanks @joeygeo .

I just managed to replicate this via Avast Chrome extension:

![image](https://github.com/wasp-lang/open-saas/assets/1536647/d90d6131-2d76-480e-a9ae-468f292752bb)

I am reopening the issue in any case, since you said Avast still reports it as problematic on your side, and I was also able to replicate it.

What we can try:
1. Go through our page, try to figure out what could be triggering this.
2. Reach out to Avast, try to get more info on what is causing this, if they will want to tell us.
3. Maybe find some other services that can check our page for any weird stuff, maybe that helps us detect what might be triggering this.

**Comment by Martinsos** [comment] 2024-06-10 18:30
I sent a false positive report to Avast, asking for help.

I also check the webpage on Google's checker, which says it is clean: https://transparencyreport.google.com/safe-browsing/search?url=opensaas.sh&hl=en .

**Comment by Martinsos** [comment] 2024-06-10 18:36
Some peculiar elements we include on the landing page are:
1. Youtube video.
2. ProductHunt Card, which is in an iframe.

**Comment by joeygeo** [comment] 2024-06-11 05:34
Did some more digging and found this from IPQS: https://www.ipqualityscore.com/threat-feeds/malicious-url-scanner/https%3A%2F%2Fopensaas.sh%2F

URL Analysis Report
:
This URL is rated as suspicious due to matching indicators of similar malicious URLs. We have detected that Fly/b5051385 (2024-06-10) is running on this server, with a hosted IP address at [66.241.124.242](https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/66.241.124.242).

**Comment by rugs07** [comment] 2024-06-11 11:07
same issue with me for AVG antivirus, I just turn off the webshield to open the opensaas site

**Comment by Martinsos** [comment] 2024-06-11 14:58
> Did some more digging and found this from IPQS: https://www.ipqualityscore.com/threat-feeds/malicious-url-scanner/https%3A%2F%2Fopensaas.sh%2F
> 
> URL Analysis Report: This URL is rated as suspicious due to matching indicators of similar malicious URLs. We have detected that Fly/b5051385 (2024-06-10) is running on this server, with a hosted IP address at [66.241.124.242](https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/66.241.124.242).



> Did some more digging and found this from IPQS: https://www.ipqualityscore.com/threat-feeds/malicious-url-scanner/https%3A%2F%2Fopensaas.sh%2F
> 
> URL Analysis Report: This URL is rated as suspicious due to matching indicators of similar malicious URLs. We have detected that Fly/b5051385 (2024-06-10) is running on this server, with a hosted IP address at [66.241.124.242](https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/66.241.124.242).

Thanks, this helps a lot! Sounds like it based the verdict on IP that our app is deployed on at Fly. I am guessing that some other app on Fly was using that IP in the past, and was doing something malicious/weird and got flagged, and now we got their IP. So it might be enough to just change that IP. I will reach out to Fly.io to see what they advise.

**Comment by Martinsos** [comment] 2024-06-11 15:48
Ok yeah, it seems it is defitively this. Turned out our client for opensaas.sh was sharing IP with other apps on Fly.io, which I wasn't aware of. I will not opt-in for a dedicate IP and set up the domain to point to this new IP and I imagine that should solve the current problem + prevent it from possibly happening in the future again.

**Comment by Martinsos** [comment] 2024-06-11 16:33
Ok, did this! A record now points to new, dedicated IP. I will leave the dynamic IP on Fly for a day or so to make sure all DNS records are updated and will remove it then.
I also made another false positive report to Avast with more info this time (info about Fly and shared IPs), so I hope that will help.

**Comment by Martinsos** [comment] 2024-06-13 12:46
I removed the dynamic IP, now we completely switched to fully dedicated IP, but that [report](https://www.ipqualityscore.com/threat-feeds/malicious-url-scanner/https%3A%2F%2Fopensaas.sh) still says we are suspicious! And now with this new IP. But what remained constant is the mention of `Fly/b5051385 (2024-06-10)`, that was also in the older report when it was mentioning old IP. So I wonder if this is really waht is triggering it. Is this machine id on the Fly? Or some part of their network? I don't know, I asked them what this is, so we can figure out what we need to change. The best I can think of is getting rid of existing Fly machines we have for the client and procuring new ones, but I would love to understand better what `Fly/b5051385 (2024-06-10)` is first.

**Comment by Martinsos** [comment] 2024-06-13 18:57
I learned that `Fly/...` is a header that Fly add's to the repsonses. But, I am not so sure Fly header is the issue anymore. I checked out our other apps hosted on Fly and they are not recognized as malicious, even though they have exactly the same header!
So either it has something to do with our page directly (URL? It uses .sh as a domain, could that be suspicious? Or word saas?), or maybe it did get flagged due to shared IP but now that flag is stuck to the URL.
So out of ideas currently except for waiting to see if false positive reports help.

**Comment by Martinsos** [comment] 2024-06-14 13:20
I removed Fly's headers by adding to fly.toml file:
```
[http_service.http_options.response]
  pristine = true
```
and that got them removed, but still doesn't help.

One thing I did though was check for https://open-saas-wasp-sh-client.fly.dev/ on IQPS, and for this one it says it is ok! This is real URL of open saas client, while https://opensaas.sh is a redirect. Meaning that the problem is not with the page itself, but with the domain. Additionally, it also reports docs.opensaas.sh as malicious, which is Astro page, so totally different code. So it must be false positive exclusively based on the domain.

If that is so, I don't see what we can do besides asking them to remove that false positive from our domain, or to actually change the domain, which I really don't want to do.

**Comment by joeygeo** [comment] 2024-06-15 01:36
I don't see this issue with other .sh domains.
I think this was just the IP issue that you mentioned earlier. Now the security firms have to update their db, which is usually at a _corporate_ pace.

**Comment by Martinsos** [comment] 2024-06-17 11:00
I probably worded it badly, but yeah I also don't think it has anything to do with the .sh domain, but with our specific opensaas.sh domain, due to getting tainted by that shared IP.
Yes I hope they will update their databases with time! I can try submitting some more reports in the future, but for now I don't have any more ideas.

**Comment by Martinsos** [comment] 2024-08-15 14:07
It seems avast doesn't mark opensaas.sh domain as malicious anymore, yay! I guess they updated their database. IPQS still marks it as suspicious domain but ok I hope that will also pass. I will close this issue for now then.

**Closed by Martinsos** 2024-08-15 14:07 UTC
Labels: shouldfix
