### ISSUE TITLE
SDK Build Error

### ISSUE THREAD

**Issue by aliammari1** [wasp-lang/open-saas#173] opened 2024-06-09 20:35 UTC
i got this error while executing wasp db migrate-dev:
🐝 --- Building SDK... ------------------------------------------------------------

[  Wasp  ] tsconfig.json(2,14): error TS6053: File '@tsconfig/node18/tsconfig.json' not found.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(1,23): error TS2688: Cannot find type definition file for 'jest'.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(9,27): error TS2304: Cannot find name 'expect'.
[  Wasp  ] ../../../../node_modules/vitest/node_modules/vite/dist/node/index.d.ts(5,41): error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.
[  Wasp  ]   There are types at '/home/aliammari/AiSaaS/app/node_modules/vitest/node_modules/rollup/dist/parseAst.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- SDK build failed with exit code: 2

❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found

**Comment by Martinsos** [comment] 2024-06-10 11:32
Duplicate of https://github.com/wasp-lang/wasp/issues/2085 -> please join us there to continue discussion!

**Closed by Martinsos** 2024-06-10 11:32 UTC
